<%-- 
    Document   : support
    Created on : 4 Mar, 2013, 12:18:30 AM
    Author     : sony
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Support</title>
        <script type="text/javascript" src="../menu/dmenu.js"></script>
        <noscript><link type="text/css" href="../menu/style.css" rel="stylesheet"></noscript>
        <style>
            *{margin: 0px;
              padding:0px}
            </style>  
        </head>
        <body>
            <form method=post>
                <table width="100%" cellpadding="0" cellspacing="10">
                    <tr>
                        <td width="100%" align="center">
                            <table width="1200px" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td height="20px" bgcolor="#C0D7E8">
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" height="33px" valign="top" style="background: url(../menu/normal_back.png) repeat-x">
                                    <!-- Deluxe Menu -->
                                    <!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->
                                    <ul id="blueMenu">
                                        <li class="istylei0"><a href="../tablet.jsp">Home</a></li>
                                        <li class="istylei0"><a href="tabdetails.jsp">Products</a></li>
                                        <li class="istylei0"><a href="software.jsp">Software</a></li>
                                        <li class="istylei0"><a href="support.jsp">Support</a>                                            
                                        <li class="istylei0"><a href="contact.jsp">Contact Us</a></li>
                                    </ul>
                                    <!-- End of Code for Deluxe Menu Items -->
                                    <script type="text/javascript" src="../menu/data.js"></script>
                                </td>
                            </tr>
                            <tr>
                                <td height="10px" bgcolor="#649DC8" style='font-size: 1px;'>
                                </td>
                            </tr>                            
                        </table>
                    </td>
                </tr>
            </table>
            <center>            
                </br></br>
                <h1>Apple</h1></br>
                <p>Any Problem go through the Quick Guide.</p>
                <p>If any Querry mail us.</p>
                <p>Go throgh the Forum for a Solution to the Problem.</p>
                </br></br>
                <h1>Microsoft</h1></br>
                <p>Any Problem go through the Quick Guide.</p>
                <p>If any Querry mail us.</p>
                <p>Go throgh the Forum for a Solution to the Problem.</p>
                </br></br>
                <h1>Sony</h1></br>
                <p>Any Problem go through the Quick Guide.</p>
                <p>If any Querry mail us.</p>
                <p>Go throgh the Forum for a Solution to the Problem.</p>
            </center>
        </form>
    </body>
</html>
